CREATE TABLE TY_LANGUAGE (	
    ID NUMBER(*,0) NOT NULL, 
	CODE VARCHAR2(20) NOT NULL , 
	NAME VARCHAR2(50) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE EN_USER MODIFY LANGUAGE NUMBER (*,0);

ALTER TABLE "TUCS"."EN_USER" ADD CONSTRAINT FK_EN_USER_LANG_TY_LANG FOREIGN KEY("LANGUAGE") REFERENCES "TY_LANGUAGE"("ID");

COMMIT;